# Dependencies
markdown:         kramdown
#highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            PRESS
tagline:          ''
description:      ''
url:              http://lanyon.getpoole.com

author:
  name:           ''
  url:            

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dessart/pressdoc
