# Dependencies
markdown:         kramdown
#highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            PRESS
tagline:          ''
description:      ''
url:              http://doc.pressblog.me

author:
  name:           ''
  url:

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dessart/pressdoc
